version: "3.9"

services:
  webapp-dev:
    container_name: "webapp-dev"
    build:
      context: .
      args:
        PUBLIC_SUPABASE_URL: $PUBLIC_SUPABASE_URL
        PUBLIC_SUPABASE_ANON_KEY: $PUBLIC_SUPABASE_ANON_KEY
    restart: unless-stopped
    networks:
      - hive
    env_file:
      - .env

networks:
  hive:
    external: true
