version: "3.9"

services:
  webapp:
    container_name: webapp
    build:
      context: .
    restart: unless-stopped
    networks:
      - hive
    env_file:
      - stack.env

networks:
  hive:
    external: true
