ersion: "3.9"

services:
  nodeserver:
    container_name: "nodeserver"
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
  networks:
    - proxy

networks:
  proxy:
    driver: bridge
